# Generated by Django 4.2.2 on 2025-09-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mailing_recipient",
        ),
    ]
