# Generated by Django 4.2.2 on 2025-09-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_mailing_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
