# Generated by Django 4.2.2 on 2025-09-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_mailing_active",
            field=models.BooleanField(default=True, verbose_name="Рассылки активны"),
        ),
    ]
