# Generated by Django 4.2.2 on 2025-09-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="messages",
                to="users.mailing_recipient",
                verbose_name="Получатели",
            ),
        ),
    ]
