# Generated by Django 4.2.2 on 2025-09-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing_recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("full_name", models.CharField(max_length=50, verbose_name="Ф.И.О")),
                ("comment", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="messages",
                to="mailings.mailing_recipient",
                verbose_name="Получатели",
            ),
        ),
    ]
