# Generated by Django 4.2.2 on 2025-09-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_mailing_recipient_alter_mailing_recipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing_attempt",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                default="Не успешно",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_mailings",
                to="mailings.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                default="Создана",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailing_attempt",
            name="data_attempt",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время попытки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing_attempt",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailings.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailing_attempt",
            name="server_response",
            field=models.TextField(verbose_name="Ответ сервера"),
        ),
        migrations.AlterField(
            model_name="mailing_recipient",
            name="comment",
            field=models.TextField(verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="message",
            name="body_of_the_letter",
            field=models.TextField(verbose_name="Тело сообщения"),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject_of_the_letter",
            field=models.CharField(max_length=30, verbose_name="Тема сообщения"),
        ),
    ]
